### ISSUE TITLE
laika-0.1.0 does not compile with record-0.2.0 

### ISSUE THREAD

**Issue by peti** [nikita-volkov/laika#1]
If you have the chance, would it be possible to get an updated version on Hackage that fixes the [outdated dependencies](http://packdeps.haskellers.com/feed?needle=laika)?

See http://hydra.cryp.to/build/523254/nixlog/1/raw for a complete build log of the error our CI environment sees after lifting the restriction from the Cabal files.

**Comment by nikita-volkov** [comment]
Sure. I'll release it soon

**Comment by nikita-volkov** [comment]
Fixed in 0.1.1
